### ISSUE TITLE
Relative Records - Duplicate key

### ISSUE THREAD

**Issue by ameyer66** [SteveIves/SqlReplicationIoHooks#17]
The generated code from the SqlIO.tpl template for loading relative records into a table results in a "Duplicate Key" error. The relative record counter is never incremented.

In the function: `function <StructureName>Load, ^val`

The following code loads a memory buffer with the record number and the data.
```
            ;;Got one, load it into or buffer
            <IF STRUCTURE_ISAM>
            ^m(inpbuf[mc+=1],mh) = tmprec
            </IF STRUCTURE_ISAM>
            <IF STRUCTURE_RELATIVE>
            ^m(inpbuf[mc+=1].recnum,mh) = recordNumber
            ^m(inpbuf[mc].inprec,mh) = tmprec
            </IF STRUCTURE_RELATIVE>
```
The issue is the `recordNumber` is never incremented. I corrected it in my template by modifying the line where the record number is being stored in the memory buffer.
```
            ;;Got one, load it into or buffer
            <IF STRUCTURE_ISAM>
            ^m(inpbuf[mc+=1],mh) = tmprec
            </IF STRUCTURE_ISAM>
            <IF STRUCTURE_RELATIVE>
            ^m(inpbuf[mc+=1].recnum,mh) = recordNumber+=1
            ^m(inpbuf[mc].inprec,mh) = tmprec
            </IF STRUCTURE_RELATIVE>
```

**Comment by SteveIves** [comment]
Thanks Andrew, nice catch. Addressed here also.
