### ISSUE TITLE
IsNumeric failed to capture a "$ERR_DIGIT 20  Bad digit encountered" for a D1 field.

### ISSUE THREAD

**Issue by ameyer66** [SteveIves/SqlReplicationIoHooks#19]
I had a very unusual occurrence of bad data that caused the IsNumeric function to not capture the bad digit. It was for a D1 field that when cast to an alpha value equated to a "."
When this value is tested in the IsNumeric function in a try/catch block by moving it into the test field 'number, d28.10', it passes and is equated to zero.
However when the SQL statement tries to insert the "." into the single digit numeric database field we get the bad digit error.
I addressed the issue by adding two lines of code to test for the "." and that the size of the field "posn" is 1.
```
    if (a_number=="." && posn==1)
        freturn false
```

**Comment by SteveIves** [comment]
Thanks for the info, Andrew. I can see how that would be an issue in earlier codebases, but we recently did a lot of enhancements to the current code base, which I believe would now catch the bad data that you mention. Specifically, we now include the following check:
```
    ;;Is there a "+", "-" or "." anywhere there?
    if %instr(1,aNumber,"+") || %instr(1,aNumber,"-") || %instr(1,aNumber,".")
        freturn false
```
