### ISSUE TITLE
incorrect parsing of date fields in <StructureName>KeyToRecord

### ISSUE THREAD

**Issue by ameyer66** [SteveIves/SqlReplicationIoHooks#23]
When the function checks the date value it is parsing the temporary record structure it is sending back instead of the key it was sent.

`if ((!<structureName>.<segment_name>)||(!%IsDate(^a(<structureName>.<segment_name>)))) then`
should read as:
`if ((!^d(aKeyValue(segPos:<SEGMENT_LENGTH>)))||(!%IsDate(^a(^d(aKeyValue(segPos:<SEGMENT_LENGTH>)))))) then`

**Comment by SteveIves** [comment]
Indeed it is. Nice catch. Fixed. Thanks, Andrew!
